### ISSUE TITLE
Wrong method name in IBfsOrderService

### ISSUE THREAD

**Issue by emileriksson** [Bricknode/Bricknode.Soap.Sdk#3]
https://github.com/Bricknode/Bricknode.Soap.Sdk/blob/e3bf7d89f79f3295953011e853198fb4b0a25424/Bricknode.Soap.Sdk/Services/BfsOrderService.cs#L99

The method for UpdateRecurringOrderTemplateAutoGiro API endpoint is named UpdateNotes. It should be UpdateRecurringOrderTemplateAutoGiroAsync.

**Comment by emileriksson** [comment]
Ok, so I've looked into it a bit more. 

There are a couple of methods that are implemented in BfsOrderService but are missing in the interface IBfsOrderService:

CreateRecurringOrderTemplatesAutogiro
UpdateRecurringOrderTemplateAutoGiro (called UpdateNotesAsync in BfsOrderService)

**Comment by simongullberg** [comment]
Thanks for pointing this out @emileriksson!

A fix is pushed and a new prerelease version (2.0.0-prerelease-d) of the Nuget package will be available in a couple of minutes.

**Comment by emileriksson** [comment]
Thanks Simon for the quick fix!
